version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-starter-kit
    env_file:
      - .env
    ports:
      - '3000:3000' # Expose app port
      - '5555:5555' # Expose Prisma Studio port
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - postgres

#   pgadmin:
#     container_name: pgadmin4_container
#     links:
#       - postgres:postgres
#     image: dpage/pgadmin4
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - '5050:80'
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     depends_on:
#       - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
  # pgadmin-data:
